<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Mason Shihab" />


<title>Data Science Sample 1</title>

<script src="site_libs/header-attrs-2.5/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/simplex.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="site_libs/anchor-sections-1.0/anchor-sections.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 41px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h2 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h3 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h4 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h5 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h6 {
  padding-top: 46px;
  margin-top: -46px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Mason's Github</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="sample1.html">Data Science Sample 1</a>
</li>
<li>
  <a href="sample2.html">Data Science Sample 2</a>
</li>
<li>
  <a href="resume.pdf" target="_blank">Resume</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Data Science Sample 1</h1>
<h4 class="author">Mason Shihab</h4>
<h4 class="date">3/27/2021</h4>

</div>


<div id="portfolio-prompts" class="section level1">
<h1>Portfolio Prompts</h1>
<p>Title of Project: Homework 4, Names Dataset</p>
<p>Brief Description of Problem: Several interesting questions and facts from the dataset were requested.</p>
<p>What problem were you solving?: See each problem below.</p>
<p>Solution: See each problem below for solution.</p>
<p>How did you solve the problem?: Data manipulation, visualization, and regression.</p>
<p>What techniques did you use? Why?: Simple R techniques, and regression. This was to confirm if intuitions regarding the data bore out in fact.</p>
<p>Were there any considerations you had to make along the way?: Yes, mostly how to prevent too many names from being processed at once, as this is a big dataset.</p>
<p>Has this project been completed yet?: Yes</p>
<p>Role: Student</p>
<p>Did you complete this work individually or as part of a team?: Individually</p>
<p>Tools / Languages Used: R, RStudio</p>
<p>Tell us about any applicable languages, business intelligence tools, databases, etc. It would also be helpful to know about any interesting libraries that you used where applicable.Relevant Links Any relevant Github repositories, write-ups, or hosted works: GGPlot, dplyr, and tidyverse were used here. The data set analyzed is known as “SSA Longtail Names.” I can provide the dataset upon request.</p>
</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>We will be loading a dataset of American names from the years 1880 to 2010. (This data set aims to be representative of the true U.S. population.) We will use this dataset to explore the popularity of names and changes in popularity.</p>
<pre class="r"><code>names &lt;- read_csv(&quot;SSA-longtail-names.csv&quot;, 
                  col_types = cols(X1 = col_skip(), sex = col_character()))</code></pre>
<pre><code>## Warning: Missing column names filled in: &#39;X1&#39; [1]</code></pre>
<pre class="r"><code>names$sum = names %&gt;% select(`1880`:`2010`) %&gt;% rowSums()

names_prop = names %&gt;% 
  pivot_longer(`1880`:`2010`, names_to = &quot;year&quot;, values_to = &quot;count&quot;) 

names_prop %&gt;% 
  mutate(year = as.numeric(year)) %&gt;% group_by(year) %&gt;% 
  mutate(annual_sum = sum(count), proportion = count/annual_sum)</code></pre>
<pre><code>## # A tibble: 12,857,388 x 7
## # Groups:   year [131]
##    name  sex       sum  year count annual_sum proportion
##    &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
##  1 Mary  F     4103935  1880  7065     201486     0.0351
##  2 Mary  F     4103935  1881  6919     192703     0.0359
##  3 Mary  F     4103935  1882  8149     221538     0.0368
##  4 Mary  F     4103935  1883  8012     216954     0.0369
##  5 Mary  F     4103935  1884  9217     243466     0.0379
##  6 Mary  F     4103935  1885  9128     240858     0.0379
##  7 Mary  F     4103935  1886  9891     255323     0.0387
##  8 Mary  F     4103935  1887  9888     247395     0.0400
##  9 Mary  F     4103935  1888 11754     299488     0.0392
## 10 Mary  F     4103935  1889 11649     288959     0.0403
## # ... with 12,857,378 more rows</code></pre>
<p>We have loaded the data and used pivot longer to obtain tidy data. See the sample above starting with Mary.</p>
<div id="proportion-of-the-top-10-names-over-time" class="section level2">
<h2>Proportion of the Top 10 names over time</h2>
<pre class="r"><code>names_prop %&gt;% 
  mutate(year = as.numeric(year)) %&gt;% group_by(year) %&gt;% 
  mutate(annual_sum = sum(count), 
         proportion = count/annual_sum) %&gt;% top_n(10, sum) %&gt;% 
  ggplot(aes(x = year, y = proportion, color = name)) + geom_line()</code></pre>
<p><img src="sample1_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Here we see that the ratio of the total population that the top ten names hold has decreased over time. This means that Americans have been naming their children with increasing diversity over time.</p>
</div>
<div id="raw-count-of-the-name-mason-over-time." class="section level2">
<h2>Raw count of the name “Mason” over time.</h2>
<pre class="r"><code>names_prop %&gt;% 
  mutate(year = as.numeric(year)) %&gt;% group_by(year) %&gt;% 
  mutate(annual_sum = sum(count), proportion = count/annual_sum) %&gt;% 
  filter(name == &quot;Mason&quot;) %&gt;% 
  ggplot(aes(x = year, y = count, col = sex)) + 
  geom_line() + labs(title = &quot;Babies named Mason&quot;)</code></pre>
<p><img src="sample1_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>It appears the name Mason exploded in popularity in the 1980’s. The true reason for this is unknown, but it could be due to renewed interest in the freemason society.</p>
</div>
<div id="biggest-changes-in-popularity-in-one-year" class="section level2">
<h2>Biggest changes in popularity in one year</h2>
<p>We will now scour the data for the biggest one year changes in name popularity.</p>
<div id="top-gainers-over-prior-year-as-a-percent" class="section level3">
<h3>Top gainers over prior year as a percent</h3>
<pre class="r"><code>names_prop %&gt;% group_by(name, sex) %&gt;% mutate(prevcount = lag(count)) %&gt;% 
  mutate(growth_factor = count/prevcount) %&gt;% 
  mutate(difference = count-prevcount) %&gt;% 
  filter(prevcount &gt; 5000) %&gt;% arrange(desc(growth_factor))</code></pre>
<pre><code>## # A tibble: 12,039 x 8
## # Groups:   name, sex [504]
##    name       sex       sum year  count prevcount growth_factor difference
##    &lt;chr&gt;      &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;     &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;
##  1 Debra      F      549898 1951  17045      6185          2.76      10860
##  2 Nicholas   M      847367 1978  16344      6067          2.69      10277
##  3 Jason      M      991561 1969  16498      7157          2.31       9341
##  4 Ashley     F      816948 1983  33280     14844          2.24      18436
##  5 Cindy      F      253906 1957  20248      9987          2.03      10261
##  6 Brittany   F      353486 1985  15433      7660          2.01       7773
##  7 Robert     M     4767995 1912  12835      6525          1.97       6310
##  8 Jacqueline F      411757 1961  10978      5651          1.94       5327
##  9 Charles    M     2335387 1912  11072      5726          1.93       5346
## 10 Deborah    F      737810 1948  11247      5831          1.93       5416
## # ... with 12,029 more rows</code></pre>
<p>The name that grew as a percent the most (with at least 5000 babies of the same name in the prior year) was Debra. In 1951 the amount of Debra babies grew from 6185 to 17045.</p>
</div>
<div id="top-losers-over-prior-year-as-a-percent" class="section level3">
<h3>Top losers over prior year as a percent</h3>
<pre class="r"><code>names_prop %&gt;% group_by(name, sex) %&gt;% mutate(prevcount = lag(count)) %&gt;% 
  mutate(growth_factor = count/prevcount) %&gt;% mutate(difference = count-prevcount) %&gt;% 
  filter(prevcount &gt; 5000) %&gt;% arrange(growth_factor)</code></pre>
<pre><code>## # A tibble: 12,039 x 8
## # Groups:   name, sex [504]
##    name      sex       sum year  count prevcount growth_factor difference
##    &lt;chr&gt;     &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;     &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;
##  1 Brittany  F      353486 2001   2929      5176         0.566      -2247
##  2 Warren    M      170805 1922   4482      7797         0.575      -3315
##  3 Brooke    F      171659 1982   3149      5329         0.591      -2180
##  4 Brittany  F      353486 2000   5176      7940         0.652      -2764
##  5 James     M     5049727 1901   4735      7246         0.653      -2511
##  6 George    M     1443869 1901   3609      5405         0.668      -1796
##  7 Christine F      581689 1953  11798     17531         0.673      -5733
##  8 Latoya    F       45301 1985   3404      5048         0.674      -1644
##  9 Jaime     F       49138 1978   4002      5903         0.678      -1901
## 10 Chelsea   F      151211 1994   7715     11289         0.683      -3574
## # ... with 12,029 more rows</code></pre>
<p>The name that shrank as a percent the most (with at least 5000 babies of the same name in the prior year) was Brittany. In 2001 the amount of Brittany babies shrank from 5176 to 2929. Interestingly, Britney Spears’ popularity may have hit a crescendo that year, after performing in the Super Bowl Halftime Show in January (alongside NSYNC and Aerosmith). This warrants further analysis!</p>
</div>
<div id="checking-on-popularity-of-brittany-over-time" class="section level3">
<h3>Checking on popularity of Brittany over time</h3>
<pre class="r"><code>names_brittany = names_prop %&gt;% filter(name == &quot;Brittany&quot;) %&gt;% 
  filter(year &gt; 1995) %&gt;% 
  mutate(Britney1 = (case_when(year &gt; 1995 &amp; year &lt; 2001 ~&quot;0-before SSBXXXV&quot;,
                                      year &gt;= 2001 &amp; year &lt; 2006 ~ &quot;1-After SSBXXXV&quot;)))

summary(lm(count ~ Britney1, data = names_brittany))</code></pre>
<pre><code>## 
## Call:
## lm(formula = count ~ Britney1, data = names_brittany)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4833.1 -1879.3  -299.6  1281.7  8961.9 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)                 4833       1261   3.833  0.00122 **
## Britney11-After SSBXXXV    -3932       1783  -2.205  0.04072 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3988 on 18 degrees of freedom
##   (10 observations deleted due to missingness)
## Multiple R-squared:  0.2126, Adjusted R-squared:  0.1689 
## F-statistic: 4.861 on 1 and 18 DF,  p-value: 0.04072</code></pre>
<p>We are comparing the five years before to the five years after. From running this simple categorical regression, we see that after Super Bowl XXXV, there was a significant precipitous drop in the amount of babies named Brittany. What about the specific spelling that Britney Spears uses? Could it be that after 2001, mothers who wanted to name their children “Brittany” decided to change the spelling to match Britney Spears?</p>
<pre class="r"><code>names_britney = names_prop %&gt;% filter(name == &quot;Britney&quot;) %&gt;% 
  filter(year &gt; 1995) %&gt;% 
  mutate(Britney2 = (case_when(year &gt; 1995 &amp; year &lt; 2001 ~&quot;0-before SSBXXXV&quot;,
                                      year &gt;= 2001 &amp; year &lt; 2006 ~ &quot;1-After SSBXXXV&quot;)))

summary(lm(count ~ Britney2, data = names_britney))</code></pre>
<pre><code>## 
## Call:
## lm(formula = count ~ Britney2, data = names_britney)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -578.4 -563.1 -280.7  366.0 1823.6 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)                578.4      229.8   2.517   0.0215 *
## Britney21-After SSBXXXV    -20.4      325.0  -0.063   0.9506  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 726.8 on 18 degrees of freedom
##   (10 observations deleted due to missingness)
## Multiple R-squared:  0.0002188,  Adjusted R-squared:  -0.05532 
## F-statistic: 0.00394 on 1 and 18 DF,  p-value: 0.9506</code></pre>
<p>We see no significant change in the spelling “Britney.” We can likely rule out that the missing “Brittanys” switched to “Britneys,” especially given the negative estimate. (However, none of this should be taken against Britney herself.)</p>
</div>
</div>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion</h1>
<p>As we can see, this names dataset can be used to analyze and interpret trends in the popularity of names over time.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
